### ISSUE TITLE
Hang on calling script that generates UI dialogs

### ISSUE THREAD

**Issue by chemxboy** [grahamgilbert/imagr#108]
I'm starting to really like Imagr.

I'm trying to replicate some of my deploystudio workflows and hit a snag.

I call a script that pops up a UI (first used CocoaDialog, now I use Pashua) to collect some info via pop-up menu to set a flag file on the destination computer.

With an NBI (generated with NBICreator) running 10.10 all is well.

With an NBI (also generated with NBICreator) running 10.11, it hangs when interacting with any of the generated UI parts. I tried using both CocoaDialog and Pashua and get the same results.  It only hangs when Imagr executes the script.  If I first open terminal and call the script, all functions as it should.  This leads me to believe it is a bug in Imagr on 10.11.  Not sure what logs might be useful for fixing.

**Comment by grahamgilbert** [comment]
System log will be useful. You can get it when you use NBICreator and choose to show the console (I THINK that's in the current build). 

However, this might be really tricky to debug. I clearly don't do this, so sharing your script wold also help.

Graham Gilbert

**Comment by chemxboy** [comment]
Looks like it may not be an issue with imagr after all.  Building a netboot image with AutoImagrNBI results in a working setup.

**Comment by erikberglund** [comment]
@chemxboy Did you include SystemUIServer (MenuBar) in the NBI created with NBICreator?

**Comment by chemxboy** [comment]
Yes, I did

**Comment by erikberglund** [comment]
Ok, I believe that might be the issue actually, I have not tested this out completely, but that is OpenGL/CL and generates a lot of strange behaviour on 10.11 as I believe they moved away from OpenGL and uses Metal instead, and the OpenGL and CL Libraries behave very differently on 10.11. I have a problem with Casper Imaging on 10.11 that won't work correctly if the OpenGL libraries are included (and SystemUIServer). I have not found the issues and what's missing (As it works on a "full" os install). So my guess that is the issue.

**Comment by erikberglund** [comment]
I am in he process of rewriting big parts of the code atm (for NBICreator) but when that is finished I will start looking into optimizing things like this. I will add this as a bug, and try to get it fixed.
