### ISSUE TITLE
Error handling pkgs & dmgs

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#109]
Currently it is possible to download a package and dmg that do not have the proper file extensions. The logic for L757 and L784 in the MainController are not doing what they are suppose to. 

To test this you can create a workflow with a pkg or dmg that has the file extension removed. Imagr will still download and copy the file to the target drive. This will cause errors during install on first run or during Imagr runtime if the `first_boot` key is set to false as we can't properly handle the pkg/dmg without a file extension.

[MainController.py#L757](https://github.com/grahamgilbert/imagr/blob/master/Imagr/MainController.py#L757)
[MainController.py#L784](https://github.com/grahamgilbert/imagr/blob/master/Imagr/MainController.py#L784)

Example:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>workflows</key>
  <array>
    <dict>
      <key>name</key>
      <string>test</string>
      <key>description</key>
      <string>test missing file extensions</string>
      <key>components</key>
      <array>
        <dict>
            <key>type</key>
            <string>package</string>
            <key>url</key>
            <string>http://localhost/imagr/munkitools-2.3.1.2560</string>
        </dict>
      </array>
    </dict>
  </array>
</dict>
</plist>
```

I can look at a PR to fix this at a later time.

**Comment by grahamgilbert** [comment]
We'd probably need a key to specify what it is then, since we handle pkgs or dmgs differently. Or choose a default, or just throw a warning. What is the best way to handle this?

**Comment by gregneagle** [comment]
Or just tell Imagr users to name their files correctly... You can code defensively and throw an error if you can't tell what kind of file you have, but I don't think you need to absolve the admin of all responsibility.

**Comment by clburlison** [comment]
I'm in that same boat as Greg I would just like an error at runtime if the file extension isn't present.

**Comment by grahamgilbert** [comment]
Good enough?

![screenshot 2015-12-15 15 38 41](https://cloud.githubusercontent.com/assets/1208495/11815188/95147dac-a342-11e5-8d67-8a9a20092601.png)

**Comment by clburlison** [comment]
:+1:
