### ISSUE TITLE
LoginLog doesn't show after reboot

### ISSUE THREAD

**Issue by physhster** [grahamgilbert/imagr#110]
Hi,
For a reason I ignore, the progress window showing the log doesn't show after imaging unless the machine is hard rebooted. I apply an admin user account package during imaging but the new computer wizard still shows. Any reason for that?

Thanks!

**Comment by grahamgilbert** [comment]
Have you used a package to skip the setup assistant either installed by imagr or in your image? Sounds like you've not done this.

**Comment by physhster** [comment]
Will running 'touch /var/db/.AppleSetupDone' first solve the issue?

**Comment by grahamgilbert** [comment]
You need to use the target volume variable as per https://github.com/grahamgilbert/imagr/wiki/Workflow-Config#scripts if you are doing this pre first boot, but yes, without looking that sounds like that would do the trick.

**Comment by physhster** [comment]
That did the trick. Thank you so much! Amazing tool!
