### ISSUE TITLE
Unattended Workflow Execution

### ISSUE THREAD

**Issue by rdrake** [grahamgilbert/imagr#112]
Imagr currently requires that an administrator enter in a password and choose a workflow.  This slows down the process of imaging a lab.

I'd like to add a feature that enables the unattended execution of workflows.

The following changes will need to be made to the workflow configuration.
- [x] A way of specifying the default workflow
- [x] A way to opt-out of the password requirement

**Comment by grahamgilbert** [comment]
I would see this as two separate feature requests, as I see utility in both (but not in my environment, so it will be a while until I would work on this - pull requests accepted, obviously!).

**Comment by clburlison** [comment]
Would this make sense as two workflow keys? `default_workflow` bool and `no_password` bool.

Then just loop through the workflows and if both are set to true run the workflow on Imagr launch. 

I'd propose that if a password is set we shouldn't auto run the default workflow, just set it as the selected menu option. Sound reasonable?

**Comment by erikng** [comment]
One of them would be a workflow key while the other would be in the primary config. 

I like the idea of selecting the default workflow but I'm thinking that might be the behavior with or without a password (using default_workflow).

**Comment by grahamgilbert** [comment]
I would go so far as to not introduce an additional key for password - if it's missing, just auto log in.

**Comment by grahamgilbert** [comment]
Exactly. And there's a difference between default workflow (the one chosen when Imagr starts) and automatically running one in my opinion. 

Sent from my iPhone

On Wed, Dec 30, 2015 at 8:34 AM -0800, "Erik Gomez" notifications@github.com wrote:

One of them would be a workflow key while the other would be in the primary config. 

I like the idea of selecting the default workflow but I'm thinking that might be the behavior with or without a password (using default_workflow).

**Comment by clburlison** [comment]
Alright, that clears up implementation questions for me. If you get a pull request by the end of the week you'll know I found time to work on this. Not sure how often I'll use this feature but worth wild if it saves me a few minutes. 

Notes: `autorun`, `default_workflow`, "no password" = allow access.

**Comment by rdrake** [comment]
This feature is complete but could use more testing.  The code currently lives in the [autorun](https://github.com/rdrake/imagr/tree/autorun) branch of my fork.

To use it:
1. You must not specify a password.
2. You must not ask for a computer name.
3. You must set the `default_workflow` key.
4. The default workflow must have the `autorun` key set to `true`.

If the above conditions are met, when Imagr starts, it begins a 30s countdown.  If the user clicks the Cancel button, they are able to select a different workflow/volume and run that.  Otherwise the default workflow is executed on the first volume.

![screen shot 2016-01-11 at 8 19 48 am](https://cloud.githubusercontent.com/assets/101562/12234617/4a87c186-b83c-11e5-9524-d430c18ad0dc.png)

Existing methods and UI elements were re-used when possible.

**Comment by grahamgilbert** [comment]
Why aren't we able to ask for a password or set a computer name? Setting an auto run workflow still saves some clicks

**Comment by grahamgilbert** [comment]
Also not sure why we need to set a workflow to autorun AND set the default workflow. If one is set to autorun then surely we want it to autorun regardless? I thought the default workflow was really a GUI thing?
