### ISSUE TITLE
A way to suppress restart at the end of a workflow

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#12]
This could take the form of a preference, or a key in the workflow.

When testing, it's helpful to be able to verify the results of a workflow before the restart occurs; I can just comment out the restart action in code right now, but would be nice to have more formal support.

**Comment by grahamgilbert** [comment]
Of the two, I'd prefer setting an option in the workflow. Rebuilding nbi's (even with AutoNBI) is a bit of a pain.

**Comment by grahamgilbert** [comment]
I started working on this in https://github.com/grahamgilbert/imagr/commit/c772f690b592729b25ca70ab6cf6636c4386eae7 but I'm not happy with it. I'm going to move it to a per-workflow option, in addition to some GUI feedback.

**Comment by grahamgilbert** [comment]
Each workflow can now have a `restart_action` key set.

`restart`: Restarts the machine. If the key isn't set, this is the default as to not break existing behaviour
`shutdown`: Shuts the machine down.
`none`: Displays a dialog with the options to shut down, restart or run another workflow. I'd like to make this the default in the future. Also doesn't actually check for `none`, will show this if anything other then `restart` or `shutdown` is set for the key.
