### ISSUE TITLE
Included workflow didn't ask for computer name...

### ISSUE THREAD

**Issue by jazz-o-mat** [grahamgilbert/imagr#120]
... if image restore task comes first.
Imagr needs to check about the name task and ask in front of the workflow.

**Comment by grahamgilbert** [comment]
Ok, so what needs to happen is:
- When before running through the workflow the first time, see if there is an included workflow in the workflow.
- If there is, iterate over every component type key and see if there's a naming task.
- If there is, show the naming tab before running everything.

**Comment by grahamgilbert** [comment]
This will be fixed in 1.0.2
