### ISSUE TITLE
Can Validateplist also check order of critical items

### ISSUE THREAD

**Issue by Daz-wallace** [grahamgilbert/imagr#124]
For example, ensuring that the partition task comes first (if present), then the image restore task (if present) then anything else

(as per Slack discussion)

**Comment by grahamgilbert** [comment]
Yep. Basically will just check if there are any non destructive items before destructive items. This will flag a warning, but proceed with the rest of the validation (since the admin may actually want this, when running a script or payload free package before deploying the image).

**Comment by grahamgilbert** [comment]
Validate plist now does this.
