### ISSUE TITLE
Unified "runWorkflowOnThread" method

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#13]
Since it seems like the goal is to provide meaningful progress feedback when a workflow runs, I think it might make more sense to build a single "runWorkflowOnThread" method that performs the various subtasks, updating the status display as it runs. This would eliminate a lot of code duplication for each of the 'doSubtaskOnThread" methods, and make it easier to do consistent progress feedback for the entire workflow.

**Comment by grahamgilbert** [comment]
Agreed. It might take a while as my pyobjc is basic at best.

**Comment by gregneagle** [comment]
I can help! I do have some experience along these lines.

**Comment by gregneagle** [comment]
(I might not be much additional help until Tuesday, when I'm back in the office and have access to a NetBoot server and test machines, etc. I imagine I could do something with VMs here at home in the meantime, but probably won't...)

**Comment by grahamgilbert** [comment]
I believe someone once said "pull requests welcome". Go for it. BSDPy is pretty easy to spin up in a VM.

**Comment by gregneagle** [comment]
we'll see. it's all about friction-of-entry for me.

**Comment by gregneagle** [comment]
I've started work on this here: https://github.com/gregneagle/imagr

**Comment by gregneagle** [comment]
And merged here: https://github.com/grahamgilbert/imagr/commit/4ca4ec9bea51b501b571daa19a11fc37434094fe
