### ISSUE TITLE
Naming computer function does not work

### ISSUE THREAD

**Issue by horizontalz** [grahamgilbert/imagr#132]
I add:
<dict>
    <key>type</key>
    <string>computer_name</string>
</dict>
to my imagr_config.plist and I get the field to input the computer name but it doesn't rename the computer.

**Comment by clburlison** [comment]
Do you have the order correct?

https://github.com/grahamgilbert/imagr/wiki/Workflow-Config#component-ordering

**Comment by grahamgilbert** [comment]
I can assure you it does work. Please post your config plist. Take care not to perform a destructive action after the naming task such as restoring an image or partitioning the disk. 

Sent from my iPhone

On Fri, Apr 29, 2016 at 10:38 AM -0700, "horizontalz" notifications@github.com wrote:

I add:

```
type

computer_name
```

to my imagr_config.plist and I get the field to input the computer name but it doesn't rename the computer.

**Comment by horizontalz** [comment]
My apologies.  I was ordering my keys the way you presented in the visual example of how not to arrange the keys!  In my haste, I didn't read the fine print.  It works as intended after placing the key after the imaging one.  Thanks for an awesome application!

**Comment by grahamgilbert** [comment]
:thumbsup:
