### ISSUE TITLE
Option to rename computer

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#14]
How do you feel about an optional text field that allows us to rename the computer on firstboot? Imagr could output a simple text file after the image process while your first-boot script could be modified to look for said file. That is the only missing feature that would allow me to drop DeployStudio.

**Comment by grahamgilbert** [comment]
I'm not _opposed_ to the idea, but I do have other solutions that I use for this (either [MacNamer](https://github.com/grahamgilbert/macnamer) or a script that just sets the name to the machine's serial number). If someone else wants to do it, it can be merged in, but it's not massively high on my list.

**Comment by vmiller** [comment]
I would definitely like to see this feature as well.  If someone doesn't beat me to it, I will probably take a stab at adding it.

**Comment by grahamgilbert** [comment]
This is partly solved by the new `script` workflow component.

**Comment by clburlison** [comment]
I think I have this solved with the following commit but would prefer a second set of eyes prior to a pull request. Feedback?

https://github.com/clburlison/imagr/commit/aeab906031fea6ff7c7123fc5da03987d4d8bae9

**Comment by grahamgilbert** [comment]
I'm mobile right now so haven't looked in xcode, but off the top of my head, I'd rather this was a tab that we can switch to prior to the workflow kicking off if we need to. - it makes it easier to separate things in interface builder.  I have a workflow in my head that I'll diagram - I was thinking of options that could be passed through the config plist like setting the name to the serial number, or to have a default prefix on the name. Now you've done the first boot script, I can probably implement this pretty easily.

**Comment by clburlison** [comment]
That sounds good to me. I understand what you are saying and I'll let someone with more experience implement that. :+1:

**Comment by vmiller** [comment]
@clburlison I did some testing with this, and found some issues.
- When a workflow contained no scripts or packages the first-boot process kept looping and retrying the rename
- It is possible for the cleanup of the first-boot directory to happen before the rename code runs.

I think this fixes that : https://github.com/vmiller/imagr/commit/30dfe6baaa89976cf811869defbd489340c7eb48

**Comment by grahamgilbert** [comment]
Chaps, please run from the latest source and add https://github.com/grahamgilbert/imagr/wiki/Workflow-Config#computer-name to your config plist. Let me know how you get on.

**Comment by clburlison** [comment]
It seems everything is working for me except for the `auto` key. When that key is set to true the workflow does not run (stuck at workflow selection screen).

**Comment by grahamgilbert** [comment]
Can you try now?

**Comment by clburlison** [comment]
Alright, now the workflow runs but the thread doesn't exit properly. When `auto` is set to true, run a workflow with the rename component and have a `restart_action` of none you are presented with the following screen. 
![screen shot 2015-05-12 at 7 25 13 am](https://cloud.githubusercontent.com/assets/2831320/7587008/6c0a15ae-f878-11e4-9c36-532cec5508fa.png)

At which point, you have to click "Run another workflow" followed by "Set Computer Name" to exit back to the main menu.

**Comment by grahamgilbert** [comment]
This should be fixed in the latest commit

**Comment by vmiller** [comment]
My fairly simple workflows seem to be working so far.  I'll pull down the latest commit and keep testing.

**Comment by clburlison** [comment]
@grahamgilbert :+1: The latest commits meet all of my use cases. A previous comment you made suggested you wanted to have the ability to add a prefix to the hostname, as such I will let you close this issue when it meets all your requirements.

**Comment by grahamgilbert** [comment]
Yes, that was the plan, but this will do for now.
