### ISSUE TITLE
Background window and desktop conflicts

### ISSUE THREAD

**Issue by MagerValp** [grahamgilbert/imagr#143]
The newly introduced background window feature was designed to hide the ugly gray screen when running from an AutoNBI-generated netboot set. It didn't take into account other runtime environments and interacts badly with them. As the first order of business to get out of this mess I propose that I add another preference key to `com.grahamgilbert.Imagr` named `background_window`, with three possible values:
- `never`: This brings back the old behavior and leaves the desktop visible. No good songs were written after 1993 anyway.
- `always`: Always open a background window, defaulting to a [grim and colorless window, with all joy removed](https://macadmins.slack.com/archives/announcements/p1463152425017026) if no `background_image` key is specified in `imagr_config`.
- `auto`: The computer is your friend. Only open a background window if `Dock.app` isn't running and the `background_image` key is specified in `imagr_config`.

I would suggest that `auto` is made the default.

Secondly, other than AutoNBI images and running from the Desktop, what other popular and/or supported runtime environments are there that need to be tested? So far [AutoImagrNBI](https://macmule.com/projects/autoimagrnbi/) and [NBICreator](https://github.com/NBICreator/NBICreator) have been mentioned on Slack - it would be good if they were added to the NetInstall section in the wiki.

**Comment by grahamgilbert** [comment]
That all sounds good to me. I don't know of any other tools to make nbis or bootable drives.

**Comment by macmule** [comment]
Just to clarify, for me adding this to AutoImagrNBI.. 

As AutoImagrNBI creates a NetBoot image with Dock & Finder etc al running, if I give people this as the option.. I should set `background_window` to always?

**Comment by clburlison** [comment]
Yes "always" would be the safe default for AutoImagrNBI.

**Comment by macmule** [comment]
@clburlison thanks.. i'll remove the frequency options from AutoImagrNBI

**Comment by clburlison** [comment]
No. The value you put as "frequency" in your pre-release if AutoImagrNBI is really `background_window` and should stay. The background URL that you added should be removed as it is now stored in the imagr config you download at run time, which allows you to dynamically choice the background image.

**Comment by macmule** [comment]
@clburlison so.. really.. dump the whole thing & leave it in the app_config?

From: https://github.com/grahamgilbert/imagr/wiki/Workflow-Config#background-image

> The background window is automatically displayed unless Imagr is running from the Finder. You can control it by changing the background_window setting in the App-Config, possible values are never, always, and auto (the default).
