### ISSUE TITLE
Bug: Startup Disk

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#148]
### Description of Issue/Question

When opening the `Startup Disk` from Imagr via the **Apple menu** the window is displayed behind Imagr.app.
### Setup

N/a
### Steps to Reproduce Issue

Inside of a NetInstall environment (AutoNBI or NBICreator) open the `Startup Disk` selector via the Apple menu. Note when selecting the Startup Disk via the `Utilities` menu the correct behavior is displayed in the current release.
### Versions Report

Tested Imagr v1.1.1 (current) and v1.0.3 with the same issue using the Apple menu. Tested in NBICreator (@clburlison) and AutoNBI (@erikng).
### References

https://macadmins.slack.com/archives/imagr/p1464979951002453

---

Update: Possible fix - https://macadmins.slack.com/archives/imagr/p1464987537002488 ,

**Comment by gregneagle** [comment]
If this only happens when using the Apple menu, this is not an Imagr issue -- Imagr is not involved in opening items from the Apple menu.

**Comment by MagerValp** [comment]
I suspect that this is related to how Imagr is launched. When an app is started from a shell by running the executable inside the app bundle (`sh$ /Applications/Imagr.app/Contents/MacOS/Imagr`), its windows appear to be handled differently than if you launch it with the `open` command.

**Comment by grahamgilbert** [comment]
I don't think there is much we can do about this. I cannot think of a better way to launch the app.

**Comment by clburlison** [comment]
I agree. This issue was more a note in case it came up again. It didn't look like it was that big of an issue since this has been open for 2 years without movement lets go ahead and close it.
