### ISSUE TITLE
Bug: Bless Bug Part 2

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#150]
### Description of Issue/Question

While debugging #122 I found that the blessing step is currently tied to the `restart_action`. This means if someone uses a workflow to image and returns to the Imagr main menu we aren't setting the bless target. This should be a separate step in `MainController.py` that is ran prior to the restart.
### Setup

N/a
### Steps to Reproduce Issue
1. run a workflow that contains an `image` component with `restart_action` set to `none`
### Versions Report

Imagr current (1.1.1) and all past. NBI tool is irrelevant.

**Comment by grahamgilbert** [comment]
I've moved the bless action to after the work on the thread has finished - this runs right before what to do with the restart is decided. Please test and let me know if this fixes things (I won't have access to real hardware until next week).

**Comment by clburlison** [comment]
Fixed!
