### ISSUE TITLE
make nbi fails if there is another /Volumes/Imagr mounted

### ISSUE THREAD

**Issue by MagerValp** [grahamgilbert/imagr#151]
### Setup

Mount a server share or external drive with a volume named Imagr.
### Steps to Reproduce Issue

Run `make nbi` with `BUILD=Release` in `config.mk`.
### Versions Report

1.1.1

**Comment by MagerValp** [comment]
Obvious workaround: unmount Imagr share before running `make nbi`. Adjusting the build script so that it doesn't make assumptions about the volume mount point would be nice though.

**Comment by grahamgilbert** [comment]
Heh, yes. It should mount to a temp file really.

**Comment by grahamgilbert** [comment]
Yes,

**Comment by grahamgilbert** [comment]
The makefile was squirrely about assigning a variable using `/usr/bin/mktemp`, so for now I'm mounting to somewhere in `/tmp`. The plan is to ditch the makefile and rewrite it in Python, which will be much easier to maintain going forward.
