### ISSUE TITLE
Feature request: LDAP/AD Authentication

### ISSUE THREAD

**Issue by gmarnin** [grahamgilbert/imagr#152]
Extend the deployment password at the login screen to support LDAP/AD authentication.

**Comment by grahamgilbert** [comment]
This is unlikely to happen to be honest. It may be possible to make Imagr use basic HTTP authentication which could then be backed by whatever you want, but binding a netboot / netinstall image to LDAP isn't going to happen.

I would take a PR for basic auth, but as it's something I am highly unlikely to need myself I won't be implementing it in the short term.

**Comment by calum-github** [comment]
FWIW this is how I achieve AD "authentication" on my NBIs. "Authorisation" is another function.

I think the problem here is that you need to have an NBI which has the kerb frameworks and the kinit binary, I don't think the NetInstall NBI's have kinit..

```
checkusercreds(){  ## Function to test user credentials - exits 0 if successful, non zero if a fail
    echo "${pword}" | kinit --lifetime=25m --password-file=STDIN --enterprise ${uname}${kerberos_domain}
    if [ $? = "0" ]; then
        test_authorization
    elif [ $? -ne "0" ]; then
        authstatus="Failed"
        echo $(date "+%a %b %d %H:%M:%S")  "[ERROR] - Authentication FAILED!"
        display_failed_auth
    fi
}
```

Should be noted that binding to a AD or LDAP server is not required at all

**Comment by grahamgilbert** [comment]
Honestly, I'm going to say use HTTP basic auth now it's been merged in. I'm considering this fixed as it's the most sensible way of doing it (see https://github.com/grahamgilbert/imagr/pull/155)
