### ISSUE TITLE
Variable for {{target_volume}} in Shell Script

### ISSUE THREAD

**Issue by horizontalz** [grahamgilbert/imagr#157]
I am placing my shell scripts externally on a fileshare along with the packages.

If I want to reference the {{target_volume}} on a shell script, how do I do so?  $1 doesn't seem to work.

**Comment by grahamgilbert** [comment]
I'll need more info on what you're doing. {{target_volume}} should work.

**Comment by horizontalz** [comment]
Let's say I'm creating a txt file on the target disk like so:
IMAGEINFO=090616
echo $IMAGEINFO >/Volumes/Macintosh\ HD/private/var/client/version/image_version.txt
so what you are saying is this should work:
echo $IMAGEINFO >{{target_volume}}/private/var/client/version/image_version.txt

**Comment by horizontalz** [comment]
I originally did you what you proposed but it didn't work that's why I posted this. 
I tried it again and using  {{target_volume}} still didn't work.

**Comment by grahamgilbert** [comment]
But I still don't know exactly what you're doing. 

> I am placing my shell scripts externally on a fileshare along with the packages.

Please post your entire config plist, otherwise I am just guessing.

**Comment by horizontalz** [comment]
<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.sinus.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>first_boot</key>
					<false/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.sinus.org/Imagr/CasperEnroll.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<false/>
					<key>type</key>
					<string>script</string>
					<key>url</key>
##  This references the script where I am trying to write a file to the target disk
					<string>http://imagr.sinus.org/Imagr2/client_info.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image for capturing for D &amp; D</string>
			<key>name</key>
			<string>Pre D&amp;D Mono 10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>shutdown</string>
		</dict>
		<dict>

**Comment by grahamgilbert** [comment]
The whole plist would be useful. The script would also be useful. It's really hard to troubleshoot without all the information.

**Comment by horizontalz** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>password</key>
	<string>1e963174c477c7038913877175d4594fd5dd7e73250c0690a1443b92235cabbcad8e26eca0fb1f1cfc4f91ffad68dec112943ee47a0b8424b528964e7e9a931c</string>
	<key>workflows</key>
	<array>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/1085-Student-061316.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/CasperCheck-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>content</key>
					<string>#!/bin/bash
# Declare &apos;$defaults&apos;.
defaults=&quot;/usr/bin/defaults&quot;
# Define &apos;kickstart&apos; and&apos;systemsetup&apos; variables, built in OS X script that activates and sets options for ARD.
systemsetup=&quot;/usr/sbin/systemsetup&quot;
kickstart=&quot;/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart&quot;
# Define &apos;$networksetup&apos;.
networksetup=&quot;/usr/sbin/networksetup&quot;
PREFS_DIR=&quot;$3/Library/Preferences&quot;
USERPREFS_DIR=&quot;$3/System/Library/User Template/English.lproj/Library/Preferences&quot;

##### End Declare Variables Used by Script #####

# Activate Adobe CC
/Library/Scripts/PAUSD/license\ file/AdobeSerialization

exit 0
</string>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>script</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.8.5 Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>10.8.5 Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>first_boot</key>
					<false/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/CasperEnroll.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<false/>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/client_info.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image for capturing for D &amp; D</string>
			<key>name</key>
			<string>Pre D&amp;D Mono 10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>shutdown</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>					
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/CasperCheck-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/staff-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image enrolls into JSS</string>
			<key>name</key>
			<string>10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_student-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_smarterbalanced-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/CasperCheck-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/elem-student-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Elementary Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>10.11.6  Primary Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_student-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_smarterbalanced-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/CasperCheck-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/student-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Secondary Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>10.11.6  Secondary Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/JD-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/staff-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image enrolls into JSS</string>
			<key>name</key>
			<string>JD-10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_student-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_smarterbalanced-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/JD-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/student-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>JD-10.11.6 Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/JLS-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/staff-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image enrolls into JSS</string>
			<key>name</key>
			<string>JLS-10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_student-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_smarterbalanced-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/JLS-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/student-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>JLS-10.11.6 Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/PH-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/staff-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Staff Image enrolls into JSS</string>
			<key>name</key>
			<string>PH-10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr2/FinalImage.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_student-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/create_smarterbalanced-1.0.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/PH-CC-QuickAdd.pkg</string>
				</dict>
				<dict>
					<key>type</key>
					<string>script</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/student-firstboot.sh</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 Student Image and enrolls into JSS</string>
			<key>name</key>
			<string>PH-10.11.6 Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/image01.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/Meraki_Agent_Smart_Installer.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/CasperShare/Packages/CasperCheck.pkg</string>
				</dict>
				<dict>
					<key>first_boot</key>
					<true/>
					<key>type</key>
					<string>package</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/PH-CC-QuickAdd.pkg</string>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys image01 and enrolls into JSS</string>
			<key>name</key>
			<string>PH-image01</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/250GB-pausd-mba-090616.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 D&amp;D Staff Image</string>
			<key>name</key>
			<string>DnD 10.11.6 Staff Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
		<dict>
			<key>components</key>
			<array>
				<dict>
					<key>type</key>
					<string>image</string>
					<key>url</key>
					<string>http://imagr.system.org/Imagr/120GB-pausd-mba-082416.dmg</string>
					<key>verify</key>
					<false/>
				</dict>
				<dict>
					<key>type</key>
					<string>computer_name</string>
					<key>use_serial</key>
					<true/>
				</dict>
			</array>
			<key>description</key>
			<string>Deploys 10.11.6 D&amp;D Student Image</string>
			<key>name</key>
			<string>DnD 10.11.6 Student Image</string>
			<key>restart_action</key>
			<string>restart</string>
		</dict>
	</array>
</dict>
</plist>

**Comment by quansAloud** [comment]
How would I counter the mirroring going on all over my phone any help? 😈 finaly though I learning this bull....

**Comment by grahamgilbert** [comment]
Sorry, I don't understand.

**Comment by grahamgilbert** [comment]
I'm going close this as you hadn't provided more information. Please feel free to reopen if you can help me more.
