### ISSUE TITLE
imagr open behind select language pane in macOS Sierra

### ISSUE THREAD

**Issue by najk** [grahamgilbert/imagr#164]
### Description of Issue/Question
When booting on macOS Sierra (with autonbi built image) imagr launches behind the select language pane. Clicking on imagr gives you the option to continue and everything works well. But it not launching on top. Unsure if this is a imagr or AutoNBI issue though.

![skarmavbild 2016-11-14 kl 14 06 09](https://cloud.githubusercontent.com/assets/1133026/20265846/897d8658-aa73-11e6-89ec-c96ec481f031.png)

### Setup
URL="https://xxx/imagr_config.plist"
REPORTURL="http://xxx/report/"
APP="/Applications/Install macOS Sierra.app" (10.12.1 16B657)
OUTPUT=~/Downloads
NBI="Imagr-10.12.1"
ARGS= --enable-nbi --add-python --ramdisk
BUILD=Release
AUTONBIURL=https://bitbucket.org/bruienne/autonbi/raw/feature/ramdisk/AutoNBI.py
FOUNDATIONPLISTURL=https://raw.githubusercontent.com/munki/munki/master/code/client/munkilib/FoundationPlist.py
INDEX="501"
VALIDATE=True
SYSLOG=none

### Versions Report
Imagr release 1.3.3
autonbi updated 2016-05-19

### References
FYI: After manually adding some libraries (from /usr/lib) running on AutoNBI Sierra was possible.
https://bitbucket.org/bruienne/autonbi/issues/10/adding-python-in-macos-sierra-missing

**Comment by grahamgilbert** [comment]
This is almost certainly an AutoNBI issue, but there's an easy was to test - use NBICreator.

**Comment by erikng** [comment]
I would also suggest using the latest commit of Imagr.

On Nov 14, 2016, at 5:31 AM, Graham Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:

This is almost certainly an AutoNBI issue, but there's an easy was to test - use NBICreator.

##

**Comment by najk** [comment]
You both are correct, it is an AutoNBI issue, using NBICreator solves "all" my problems.
