### ISSUE TITLE
Imagr crashes if timeapi.org returns unexpected data

### ISSUE THREAD

**Issue by chymb** [grahamgilbert/imagr#169]
### Description of Issue/Question

Imagr 1.3.8 Crashes when launched

### Steps to Reproduce Issue
1) Download the latest release DMG
2) Mount the DMG
3) Launch Imagr 1.3.8 from the DMG

### Versions Report
Production [release](https://github.com/grahamgilbert/imagr/releases/latest) (v.1.3.8)

**Comment by grahamgilbert** [comment]
Fixed in 1.3.8.1
