### ISSUE TITLE
Description text box for the workflows is not scrollable

### ISSUE THREAD

**Issue by calum-github** [grahamgilbert/imagr#172]
### Description of Issue/Question
When you enter more text into the `description` key than the display box can hold, it _should_ show a scroll bar allowing the user to scroll to see the remaining text.

### Setup
Imagr 1.3.8
10.12.2 NBI (Full netboot environment created with AutoImagrNBI)

### Steps to Reproduce Issue
Enter more than 18 lines of text into the description 

See attached screenshot for reference

![screen shot 2017-01-19 at 1 35 11 pm](https://cloud.githubusercontent.com/assets/7887711/22091820/3e7c4ba4-de4d-11e6-9290-2e76c74d4f7b.png)

**Comment by grahamgilbert** [comment]
So it looks like we need to recalculate the size we need to make the box when the description updates. I'm not sure on how to do this.
