### ISSUE TITLE
Imagr logs a crash if a volume is unmounted

### ISSUE THREAD

**Issue by MagerValp** [grahamgilbert/imagr#174]
### Description of Issue/Question
If a volume is unmounted while Imagr is running a crash with traceback is logged.

### Setup
Start image with a usb stick inserted.

### Steps to Reproduce Issue
Eject usb stick.

### Versions Report
Private fork from master branch a3b39a634651214dd00f28a6ce8f4fdc3b0fb852

### References
[unmountcrash.txt](https://github.com/grahamgilbert/imagr/files/723219/unmountcrash.txt)

**Comment by MagerValp** [comment]
The offending line appears to be https://github.com/grahamgilbert/imagr/blob/09ea73be95cb0f64f851e968a188b14434c13af8/Imagr/MainController.py#L270 and unless I'm mistaken it should be `self.targetVolume.mountpoint`? If that is the case there are a few other instances as well:

https://github.com/grahamgilbert/imagr/blob/09ea73be95cb0f64f851e968a188b14434c13af8/Imagr/MainController.py#L274
https://github.com/grahamgilbert/imagr/blob/09ea73be95cb0f64f851e968a188b14434c13af8/Imagr/MainController.py#L838

**Comment by clburlison** [comment]
One note on this issue, I needed imagr to be running a workflow to retrieve this error having the application open was not enough. At least that is the only way I was able to replicate this issue.
