### ISSUE TITLE
Setting time with http fails to respect timezone

### ISSUE THREAD

**Issue by MagerValp** [grahamgilbert/imagr#177]
### Setup
Using an https repo, start Imagr from an NBI with the timezone set to something other than GMT/UTC, without access to ntp, and with the clock wrong enough that SSL fails.

### Steps to Reproduce Issue
Launch Imagr. Get error.

### Versions Report
f0340f67ec13044f31bd508eb8998df4e1ec0b22 

### References
https://macadmins.slack.com/archives/imagr/p1488269375003867

**Comment by MagerValp** [comment]
So the issue here is we get a GMT timestamp from Apple, but then format it without timezone info and feed that to `/bin/date`:

https://github.com/grahamgilbert/imagr/blob/f0340f67ec13044f31bd508eb8998df4e1ec0b22/Imagr/Utils.py#L431-L435

**Comment by grahamgilbert** [comment]
So the choice is either read the current time zone and manipulate the date or change the time zone. What I find really strange is that I see no errors when using this in PST, Dublin or Singapore and Japan.

**Comment by MagerValp** [comment]
Needs testing, but it might be as trivial as passing `TZ=GMT` to `Popen`:

    >>> _ = subprocess.Popen(["/bin/date"]).communicate()
    Tis 28 Feb 2017 21:25:39 CET
    >>> _ = subprocess.Popen(["/bin/date"], env={"TZ": "GMT"}).communicate()
    Tue Feb 28 20:25:53 GMT 2017

**Comment by grahamgilbert** [comment]
This was added in https://github.com/grahamgilbert/imagr/commit/a73b16e40fe3ec5f5e0242a8057e89d88c1def29
