### ISSUE TITLE
Packages/DMGs with spaces will fail if using gurl

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#195]
I found a long-standing bug with imagr, where if you pass `%20` to packages/dmgs, it will fail.

Since this issue impacted startosinstall/ramdisk, I have fixed it in https://github.com/grahamgilbert/imagr/pull/190

We can close this issue once merged.

**Comment by gregneagle** [comment]
To clarify: if the URL for a package contained %20 (a URL-escaped space) it triggered a `ValueError: 'Too few arguments for format string [cur:1/len:1]'` exception and prevented download.

**Comment by erikng** [comment]
Closing - fixed with https://github.com/grahamgilbert/imagr/pull/190 being merged
