### ISSUE TITLE
Does not work with macOS 10.13.4 Installer

### ISSUE THREAD

**Issue by peteostro** [grahamgilbert/imagr#205]
### Description of Issue/Question
Using the 10.13.4 macOS installer the script fails to copy /Scripts/postinstall_actions/update
This is because the folder and file no longer exists. 
There is only a scripts folder in FirmwareUpdate.pkg, no postinstall_actions folder and no update script. (there is a preinstall and postinstall scripts they look exactly like the previous ones)

Im not sure if using a previous update script will work.

### Setup
(Please provide relevant configs. If the config is long you can attach them to this issue by changing the extension to `.txt`. Be sure to remove sensitive info.)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Production [release](https://github.com/grahamgilbert/imagr/releases) and which version (v.1.X.X) or master branch. Please also include NBI creation tool used.)

### References
(Remove this section if not relevant)

**Comment by gregneagle** [comment]
What is "the script" you refer to? What _specifically_ does not work with macOS 10.13.4 installer?

**Comment by peteostro** [comment]
Sorry the FirmwareUpdateStandalone script to create the FirmwareUpdateStandalone.pkg

the update script that is supposed to be in the FirmwareUpdate.pkg Is not there in 10.13.4

**Comment by gregneagle** [comment]
I don't think that script is part of Imagr or supported by the developers of Imagr. If it doesn't work any longer, you'll need to fix it or not use workflows that depend upon it. The script was an unsupported hack from the very beginning.

**Comment by grahamgilbert** [comment]
If you care about firmware updates etc please use startosinstall.

Sent from my iPhone
________________________________
