### ISSUE TITLE
Auto key of computer_name component ignored when part of included workflow

### ISSUE THREAD

**Issue by yagmot** [grahamgilbert/imagr#211]
### Description of Issue/Question
When the computer_name component is part of an included workflow, the auto key is ignored.

### Setup
[testconfig.txt](https://github.com/grahamgilbert/imagr/files/2012198/testconfig.txt)

### Steps to Reproduce Issue
Included workflow with computer_name component and auto key set to true

### Versions Report
1.4.1
NBI is 10.13

**Comment by grahamgilbert** [comment]
Can you elaborate on the behavior please. It seems like the complete opposite of #133 which would be very difficult to achieve.

**Comment by yagmot** [comment]
Sorry for the confusion. This is the same issue. I will close this because it is a duplicate.
