### ISSUE TITLE
com.apple.osinstall error -3 on OS X 10.13.4 if workflow writes to formatted target before startosinstall

### ISSUE THREAD

**Issue by intestinate** [grahamgilbert/imagr#213]
### Description of Issue/Question
I'm trying to use Imagr like in the following scenario:

1. Wipe HD (Preferably as APFS)
2. Set computer_name and install one package for first_boot (SuppressSetupAssistant-1.0.pkg)
3. Install OS X 10.13.4 (or 10.13.5) from standard wrapped disk image.

My issue is that step 2 and 3 only succeeds if I omit step 1.

To clarify; if I erase the HD (either through Imagr workflow or Disk Utility), then perform step 2 (manually verifying that the correct files are copied to the target volume), then start "startosinstall" as the last and only component of a workflow - the OS X installer will fail with "com.apple.osinstall error -3". (See attached screenshot)

If I do step 1, omit step 2, then run step 3 - OS X installs fine.

I can then run Imagr again, omit step 1, then run step 2 and 3 - OS X installs fine and my first_boot package executes as intended.

Alas, for my deployment automation to actually save time, I really need to be able to do all steps in one go.

I've tried two different Macs (MacBookPro12,1 and MacBookPro14,1) and OS X versions 10.13.4 and 10.13.5. I've also tried to format the target volume both as HFS and APFS.

### Setup
Please see imagr_config.plist.txt attached

### Steps to Reproduce Issue
1. Erase HD
2. Perform any kind of workflow action that writes files to target volume
3. startosinstall

Please see ia.log.txt attached (output from macOS Install Data/ia.log after a failed OS X install attempt)

### Versions Report
Imagr - master branch
bsdpy - master branch
AUTONBIURL=https://raw.githubusercontent.com/bruienne/autonbi/master/AutoNBI.py
AUTONBIRCNBURL=https://raw.githubusercontent.com/bruienne/autonbi/feature/ramdisk/rc.netboot
FOUNDATIONPLISTURL=https://raw.githubusercontent.com/munki/munki/master/code/client/munkilib/FoundationPlist.py

[ia.log.txt](https://github.com/grahamgilbert/imagr/files/2070055/ia.log.txt)
[imagr_config.plist.txt](https://github.com/grahamgilbert/imagr/files/2070056/imagr_config.plist.txt)
![img_20180525_155209](https://user-images.githubusercontent.com/2012044/40943072-f2ca7cba-681d-11e8-8314-b7eed69303ab.jpg)

**Comment by grahamgilbert** [comment]
This is a known issue that will probably be fixed with #212

**Comment by intestinate** [comment]
Thanks guys!
I can confirm that #212 solves my issue.
