### ISSUE TITLE
first_boot LaunchDaemon does not get created when startosinstall is called via included_workflow

### ISSUE THREAD

**Issue by blinvisible** [grahamgilbert/imagr#216]
### Description of Issue/Question
When `first_boot` components are combined with a `startosinstall` component that is called via `included_workflow`, the required launchd files to execute the `first_boot` items do not get created or installed to the target volume.

### Setup
[imagr_startosinstall_include_bug_config.txt](https://github.com/grahamgilbert/imagr/files/2150134/imagr_startosinstall_include_bug_config.txt)

### Steps to Reproduce Issue

1. Modify attached config file to use correct URL paths for environment. Upload config file to Imagr repo. Create/update NBI to use that file. Upload NBI to NetBoot server.

2. NetBoot to new/updated NBI.

3. Select and run a workflow.
    - For an example of a working first_boot execution, run the **SUCCESS) explicit startosinstall** workflow of attached config file. Note that both `{{target_volume}}/.imagr/first-boot` and `{{target_volume}}/Library/` with the appropriate contents get correctly created during workflow execution.

    - For an example of a failed first_boot execution, run the **FAILURE) include startosinstall** workflow of attached config file. Note that `{{target_volume}}/.imagr/first-boot` gets created, but `{{target_volume}}/Library/` does not get created, and no LaunchDaemon exists to execute upon reboot to the target volume.

### Versions Report
- Branch: master
- Release: 1.4.2
- NBI: AutoNBI 10.13.5

**Comment by grahamgilbert** [comment]
@mosen @MagerValp @a-zaleski Any of you fancy taking a look? It should be relatively simple (just making sure the first boot tools get copied whenever there is a first-boot item), but I am not going to get to look at this for a while.
