### ISSUE TITLE
Imagr (High Sierra) preventing reboot during install workflow

### ISSUE THREAD

**Issue by jeffest-jeff** [grahamgilbert/imagr#218]
### Description of Issue/Question
When running a workflow (which includes 3 packages...local admin, disable setup assistant, disable icloud and diagnostics), when it gets to startosinstall and tries to reboot, it get's stuck. 

Error message...
"imagr interrupted restart. To continue restarting, quit imagr". 
Quitting doesn't work, I have to force quit imagr before reboot continues on it's own.

Once it goes through the install, it generally fails to skip the setup assistants, asks me to create a new user, then reboots after it creates a user, then it hangs once the progress bar reaches the end (last time it hung was overnight).
- this might be a package ordering issue...i'm still testing.

### Setup
(Please provide relevant configs. If the config is long you can attach them to this issue by changing the extension to `.txt`. Be sure to remove sensitive info.)
imagr_config.plist.txt attached
[imagr_config.plist.txt](https://github.com/grahamgilbert/imagr/files/2267247/imagr_config.plist.txt)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Netboot into the 10.13.6AutoImagrNBI.nbi image.
2. Enter the password
3. Run the only workflow, wait.
4. Force quit Imagr, Mac should reboot and start the installer.

### Versions Report
(Production [release](https://github.com/grahamgilbert/imagr/releases) and which version (v.1.X.X) or master branch. Please also include NBI creation tool used.)
Imagr 1.4.2 (581)
AutoImagrNBI 1.4.0 (28)
macOS High Sierra 10.13.6

**Comment by grahamgilbert** [comment]
As stated in the wiki, startosinstall does not work with AutoImagrNBI. 
https://github.com/grahamgilbert/imagr/wiki/startosinstall-Notes#sip-and-startosinstall
