### ISSUE TITLE
Add json as a configuration file type

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#27]
Because this is running on Linux and is hosted on a web server, it would be good to support json as a config file format. 

One could imagine a web server piece that dynamically serves up the json file based upon various conditions (the netboot set location, some sort of fact, etc). Obviously this would be left up to the person implementing their imagr server. 

I think using plist is fine because admins are familiar with it, but json is far more common on web servers and are even supported by the default python install on almost everything.

**Comment by gregneagle** [comment]
Disagree. JSON maps fairly well to plists, but it's not perfect. For example, there's no canonical way to represent a date in JSON, or distinguish between integers and floats (they are all numbers).

This tool is for managing OS X and should use OS X's native structured data representation. Supporting JSON and plist formats will just add code complexity.

**Comment by keeleysam** [comment]
plistlib is widely available as part of the standard Python library on
every operating system since 2.6.

I believe that JSON would confuse more than it could help.

On Wed, Apr 22, 2015 at 9:10 PM, Greg Neagle notifications@github.com
wrote:

> Disagree. JSON maps fairly well to plists, but it's not perfect. For
> example, there's no canonical way to represent a date in JSON, or
> distinguish between integers and floats (they are all numbers).
> 
> This tool is for managing OS X and should use OS X's native structured
> data representation. Supporting JSON and plist formats will just add code
> complexity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/grahamgilbert/imagr/issues/27#issuecomment-95422384.

## 

Samuel Keeley

**Comment by grahamgilbert** [comment]
Python, Ruby and Node.js all have the ability to read and write plists, so I'm going to stick with plists. I've written apps that serve plists with Python before that worked fine (Sal+).

**Comment by natewalck** [comment]
Ok, thats cool. I was just hoping to get some diversity here, especially when considering other environments. json is pretty much the standard for getting data back from a web API and therefore if you are integrating with other systems that are using web standards, this could make it easier, whereas plists are pretty unique to OS X.
