### ISSUE TITLE
Password field no longer has focus

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/imagr#28]
Following https://github.com/grahamgilbert/imagr/commit/de9d8f0179256fb9715bb6246a1ef153228f8945, the password field doesn't have focus when the app opens. Also, an incorrect password error is given when the field gets focus.

**Comment by gregneagle** [comment]
I noticed that as well, and was working on the issue last night, but did not come up with a solution. Will revisit today. The field is actually active -- you can start typing and characters will appear in it, but there is no visual indication.

As for the second bit -- I think you/we want to change it so the field sends its action when the enter key is pressed, not on "end editing".

**Comment by gregneagle** [comment]
The more I look at this, the more this appears to be intended behavior for NSSecureTextFieldCell in Xcode 6. I can add a second (non-secure) field to the view, and when it becomes first responder, the text-insertion caret is visible. Hit tab to return focus to the password field and the text insertion point disappears. I added the focus ring back to the field so I could see it was indeed being made first responder.

I have at least one possible workaround to test later.

**Comment by grahamgilbert** [comment]
Solved in https://github.com/grahamgilbert/imagr/commit/744d3e83ea96e98f3451224ca83a9e90786ee3a0
