### ISSUE TITLE
Imagr takes a very long time to startup: optimize/replace macdisk.MountedVolumes() ?

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#32]
This might be NBI-dependent, but when testing on a DeployStudio NBI, Imagr takes upwards of 20+ seconds to become usable. A big chunk of that time is in macdisk.MountedVolumes().

Looking through the code, it ends up calling diskutil info -plist for every device id, which is incredibly slow.

I'd like to look at ways to speed this up.

**Comment by clburlison** [comment]
In my tests using a AutoNBI created NBI, Imagr takes less than 2 seconds to load. Could it be the fact that you are loading the Imagr.app from the /DSNetworkRepository/ which itself is a mounted drive?

**Comment by gregneagle** [comment]
Two seconds until the password field is available to type in?
The app _launches_, then spends a lot of time displaying "Application Starting...". It's that part I want to speed up.

**Comment by clburlison** [comment]
Yes. Roughly two seconds for the "Application Starting..." message to finish. At which point I am able to type in the password field.

**Comment by gregneagle** [comment]
OK, then if when run from the intended and supported AutoNBI-built NBI if it isn't glacial, the priority here is much lower.

**Comment by grahamgilbert** [comment]
I've not been getting 20-second waits - more like 5-10. But this is in a Fusion VM or a crappy old iMac I have for testing. I'm going to be testing on decent hardware next week.
