### ISSUE TITLE
Clicking on Workflow Description changes selected Workflow

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#34]
Steps to reproduce:
1. Have a config plist with more than one workflow
2. Upon login select a workflow other than the first workflow
3. Click in the "Workflow Description" field

Result: Selected workflow resets to the first workflow in the config.

This actually happens when you click on in the description field on the first workflow but cannot visually see it happen.

**Comment by grahamgilbert** [comment]
Thanks, nailed it.
