### ISSUE TITLE
UI reorg

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#35]
I didn't make this a pull list because it might be not a direction you are interested in.

https://github.com/gregneagle/imagr/commit/2719ef0c8d8175238892620f4ef8d1ca6c4780a5

This moves the login and main views into a tab view, which makes switching views easier, and allows us to add more views without going crazy trying to edit them in InterfaceBuilder.

As an example I added a new startup view that replaces the sheet.

It might be nice to add an "empty" view or "error" view we switch to when we don't find a server url or any writable volumes, etc. (instead of trying to hide all the controls, etc)

Since this is a pretty dramatic set of changes I thought I'd let you look at my clone first before deciding if this is a direction that makes sense.

(There's additional cleanup to be done if you decide this is a direction you want to go, but I don't want to do all the cleanup work if you don't want to go this way.)

**Comment by gregneagle** [comment]
Password field still doesn't show the insertion point, though. :-(

**Comment by gregneagle** [comment]
OK: as of this https://github.com/gregneagle/imagr/commit/744d3e83ea96e98f3451224ca83a9e90786ee3a0

I did so some of the code cleanup, and the insertion point is showing in the password field again.

**Comment by grahamgilbert** [comment]
Yes, I like it. Much easier to work with. I've already made a start on the error handling, so getting this merged ASAP would be good.
