### ISSUE TITLE
Packages in a DMG for first boot

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#4]

**Comment by gregneagle** [comment]
Not convinced there is a need for this; the workflow could mount the dmg and copy the packages to the first-boot folder. No need to support dmgs at first boot.

**Comment by grahamgilbert** [comment]
That was the intention. 

On Saturday, 18 Apr 2015 at 17:10, Greg Neagle notifications@github.com, wrote:

Not convinced there is a need for this; the workflow could mount the dmg and copy the packages to the first-boot folder. No need to support dmgs at first boot.

**Comment by natewalck** [comment]
I believe this was taken care of in commit #24
