### ISSUE TITLE
Allow dynamic selection of image

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#46]
The goal is to allow an arbitrary script to run and select which image to use during the apply image step. It does not need to be exactly as listed below, but having the functionality is super helpful, especially if you want one master workflow for support folks to run.

An example workflow:
- You have a vanilla image that works on all machines except the new MacBook
- You run a script to determine which machine type is netbooted
- You output which image you would like to be applied 
- The Image task continues as usual

**Comment by keeleysam** [comment]
I think this could be broadened a bit to allow dynamic selection of any workflow.

DeployStudio does this by assigning each workflow a UUID, so you can have a workflow item which selects other (optionally hidden) workflows by running a script which outputs the UUID.

This could be useful for additional conditionals, and even optionally skipping imaging if you can test a volume to see if it is clean.

**Comment by groob** [comment]
Assigning a UUID to each workflow also has the benefit of allowing third party tools to manage each workflow in `imagr_config.plist` independently of each other. 

I do this server side in [imagr-server](https://github.com/groob/imagr-server/tree/master/sample_repo/workflows) to manage and store workflows as separate files. 
Adding UUIDs to imagr_config.plist would be a good change, but it will probably break compatibility with current versions.

**Comment by gregneagle** [comment]
Adding new keys to a plist should not affect older software that is not expecting those keys; they would just be ignored.

**Comment by grahamgilbert** [comment]
I'm not too bothered about breaking existing functionality - the admin should update their NBI before implementing new features in their config plist. Anyway, I'm open to ideas about this. I'm not able to work on Imagr for the next month or so, but I'll happily merge in a PR that implements this.

**Comment by grahamgilbert** [comment]
Now included workflows are in, the next step is to extend that to allow for a script to determine the workflow name.

**Comment by groob** [comment]
@grahamgilbert I see that a default workflow key was added in https://github.com/grahamgilbert/imagr/pull/114. The key uses the workflow name, making the requirement that names must be unique. It's not a problem, but also not ideal.

Before workflows-in-workflows are a stable release, would it be possible to make workflow reference other workflows use a UUID rather than a name?

**Comment by grahamgilbert** [comment]
UUIDs aren't going to happen. The requirement always has been that workflow names are unique. I see no benefit of introducing this additional complexity when you can just make workflow names unique. Why is it not ideal?

**Comment by groob** [comment]
Even if names are unique, renaming a workflow will require changing the name everywhere it is referenced.

UUID's are a better solution because they allow for additional tooling and make references to other workflows/objects easier to write.

**Comment by grahamgilbert** [comment]
> Even if names are unique, renaming a workflow will require changing the name everywhere it is referenced.

Search and replace in a text editor?

> UUID's are a better solution because they allow for additional tooling and make references to other workflows/objects easier to write.

What? How? Convince me! This is significant work, so I'm not going to do it unless I'm convinced.

**Comment by gregneagle** [comment]
UUIDs would actually make things _harder_ for people manually creating/editing their workflow plists as UUIDs aren't terribly human-friendly.  I only need to know your name is "Victor", I don't need to know your Social Security Number as well in order to refer to you here.

With a dedicated workflow plist editor, separating the "human-readable name" from a "unique identifier" would have benefits, but I definitely understand Graham's reluctance to implement them without more convincing of the need.

**Comment by groob** [comment]
I agree that if someone will be editing the imagr_config.plist file by hand, then using names is more user friendly. 
Where I see UUIDs as important is supporting tools and addons on top of imagr - like a workflow editor. 
It's not so hard to imagine given Imagr's quick adoption in the community, that someone will want to create a GUI or WebUI on top of editing workflows. 

I agree that it's a lot of upfront work to do. I also see this as an inevitable change that someone will have to make in the future. Unfortunately, I don't have the bandwidth to create a PR for the UUID feature right now, so I'll stop arguing for it, but maybe someone else is interested.

**Comment by grahamgilbert** [comment]
We've got this now with the ability to select an included workflow based on the output of a script. WIN
