### ISSUE TITLE
Handle errors when Packages and Images aren't available

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/imagr#48]
Imagr will currently crash when it cannot download or install workflow components. There should be an error displayed when this happens.

**Comment by natewalck** [comment]
Should it bail the workflow when this happens as well? I think this would be the correct behavior as I'd rather have a failed workflow than one that is half-working.

**Comment by natewalck** [comment]
After looking at the code, it seems like we need a standard way of handing failures out of Utils.\* and into the main thread. It looks like return False is pretty common, so should that be the same here as well?

Then in MainController.py, we can just run it, test the results and abort workflow if False, unless there is a better way.

**Comment by grahamgilbert** [comment]
Fixed in #54
