### ISSUE TITLE
munki bootstrap is killed by reboots

### ISSUE THREAD

**Issue by JDHatman** [grahamgilbert/imagr#49]
my plist
https://gist.github.com/JDHatman/d90095854831359c9f1a

All pre_first_boot images/packages work.
All first_boot packages install successfully, one of which is a munki kickstart.
Before Imagr reboots from the first_boot installs, Munki has already started.  Imagr reboots shortly into the Munki run.
After the reboot, Munki runs again.  There is a second reboot, for no apparent reason.  Again, interrupting the Munki run.
After the second reboot, the kickstart I initiated for Munki has just given up and Munki doesn't run.  This leaves the computer is a pretty useless state since Munki installs all the relevant bits like accounts and such.  
I can boot into Recovery and manually re-touch .com.googlecode.munki.checkandinstallatstartup and after rebooting Munki will run as expected and "finish" my imaging process.

I have two workflows.  I noticed that the same pattern occurs when I use only the kickstart workflow (assuming there is a usable image already on the machine). However, using this workflow, the Munki run will continue even after getting interrupted by two reboots.

I realize that this isn't necessarily an issue with Imagr.  More or less providing info from my experiences.

**Comment by grahamgilbert** [comment]
I've not seen a munki bootstrap killed by it, but the first boot script was pulled mostly from my first boot package, so it could definitely do with some work.

**Comment by gregneagle** [comment]
One should not mix-and-match first-boot installs and Munki bootstrapping. Both are trying to the same thing at the same time. Do one or the other; not both.

**Comment by gregneagle** [comment]
(To clarify: if you use Imagr to install the Munki bootstrap pieces immediately (not at first boot), and then reboot, the Munki bootstrap behaves as expected.)

**Comment by JDHatman** [comment]
I follow the same logic in DS.  Munki bootstrap is installed on first boot.  
1st reboot - DS finalize runs, installing Munki, a managed installs plist, and kickstart.
2nd reboot - munki boostrap runs and installs all software I need.

I think, though, I just realized the difference.  In DS, munki isn't installed til the first boot.  In Imagr, I have it installed pre_first_boot.  I changed it to first boot and now the launchd isn't yet active, thus delaying the kickstart til the next reboot.  All works as it should now.
1st reboot - Imagr first_boot script installs munki, munki kickstart (launchd isn't yet active so kickstart doesn't kick-off yet)
2nd reboot - kickstart starts to run munki, but still there is a 3rd reboot for no reason, interrupting munki.
3rd reboot - kickstart doesn't run again by itself. 

I may have to rethink how I have this set up.

**Comment by gregneagle** [comment]
Looks to me like some of the first-boot logic could be adjusted: If we don't find any scripts or pkgs, cleanup but do NOT restart, as there's no reason to.

**Comment by grahamgilbert** [comment]
I've changed the first boot script to only reboot if it's run things (allowing for failure - it will retry packages if they fail to install) in 80f1da5.

**Comment by JDHatman** [comment]
I assume this is related to the changes you made earlier, but now after the first-boot items are installed, the log window never goes away.  Everything successfully installs, but you have to manually send the reboot command before it will continue.
![screen shot 2015-04-27 at 9 04 34 pm](https://cloud.githubusercontent.com/assets/6548062/7361626/7ae784e2-ed21-11e4-8772-c580172f8a93.png)
