### ISSUE TITLE
A generic script task (like DS)

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#5]

**Comment by natewalck** [comment]
For this, I was thinking we could do something similar.

This would probably piggyback on to the existing first-boot script and operate in a similar fashion.

There should possibly be a concept of the order in which things should be installed as well, so you could run a script, install a package, then run another script, etc.

**Comment by grahamgilbert** [comment]
Working, tested. Both `pre_first_boot` and firstboot are available.
