### ISSUE TITLE
Apps from the Utilities menu don't open in an AutoNBI image

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/imagr#55]
@natewalck I choose you!

**Comment by natewalck** [comment]
Should be fixed in #56 

I'm testing it now, because apparently I test after PRs.

**Comment by natewalck** [comment]
Yep, it works!

**Comment by grahamgilbert** [comment]
Certainly does!

![screenshot 2015-04-30 17 22 47](https://cloud.githubusercontent.com/assets/1208495/7417469/2a28e1d8-ef5e-11e4-932a-259329e126b6.png)
