### ISSUE TITLE
A better way to open Disk Utility

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#6]
From Graham: The current method is just a hack - there's beach balling galore

**Comment by gregneagle** [comment]
I personally would prefer a setup more like the OS X Utilities you get when booted from Recovery partition, and Imagr is just one of the available utilities: Disk Utility and Terminal among the others.

**Comment by natewalck** [comment]
Perhaps this could be an optional setting in the NetBoot set:

By default, boot directly to Imagr.

If SomeVar = True, boot to the main recovery window where Imagr.app is one option.

This would require the following functionality to be added:
- Add Imagr.app to the Recovery Boot window (if it isn't already)
- Add a preference for booting to the recovery window rather than imagr
- modify the rc.imaging script example to read the aobve preference and take the correct action.

**Comment by grahamgilbert** [comment]
Hacking on that is definitely a route I don't want to go down. I'll just be chasing after whatever apple decide to do with that. I'll raise separate issues for menu items for opening Terminal and Disk Utility (maybe others).

This issue purely refers to Disk Utility being opened on the main thread and behind the main Imagr window.

**Comment by natewalck** [comment]
By default, I think AutoNBI boots to the recovery window. So it would just be a matter of modifying rc.imaging and adding something to the menu. 

If you don't want to bother with this method, thats fine, although I think it is more Apple-y to use their Recovery window to launch stuff.

**Comment by natewalck** [comment]
Actually, this seems like an issue outside of Imagr altogether.

Adding things to the menu in recovery would be AutoNBI functionality, not Imagr functionality. So if you still want quick access to those tools, then obviously that needs to happen here (via Menu, etc).

I fiddled with AutoNBI and got to this state, which works quite well and is a simple plist file edit:

https://carousel.dropbox.com/photos/cc/gFJIXdfLjTUaLUe

Some classy photos there ;)

This method is like what Greg mentioned and can be done without modifying Imagr.

**Comment by grahamgilbert** [comment]
I like it, but agree that this is now outside of imagr.

**Comment by grahamgilbert** [comment]
But this does bring me back to the original issue - We need to find a way of opening Disk Utility without it opening behind the main imagr window.

**Comment by gregneagle** [comment]
Since we can use PyObjC, I'm pretty sure one of the NSWorkspace methods should be able to help.

https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html

I'd start with `NSWorkspace.sharedWorkspace().launchApplication_("path/to/Disk Utility.app")`

**Comment by grahamgilbert** [comment]
Excellent - I saw that but was struggling with the syntax.

**Comment by grahamgilbert** [comment]
Looks like I was too eager. This doesn't work in an AutoNBI image.
