### ISSUE TITLE
The road to 0.0.1

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/imagr#61]
I've been amazed with the speed we've got Imagr from my crappy code to something useful, so I thought it would be helpful to start thinking about what is left to do before we can do an initial release. In my opinion, we need to:
- Adjust the Makefile to build an NBI from the GitHub release rather than the development code
- Fully document the options (probably move to the Wiki for this rather than the ever expanding Readme)
- A tool that will validate the configuration plist's syntax

Anything else?

**Comment by clburlison** [comment]
If you create the initial Wiki page I can help with that!

**Comment by grahamgilbert** [comment]
@clburlison Thanks, wiki has been created.

**Comment by grahamgilbert** [comment]
Hey @clburlison, have you copied everything over? It looks like it to me, but just wanted to check before I neuter the readme.

**Comment by clburlison** [comment]
Yeap. The wiki has everything is copied. 

Also, I have an update to the makefile that pulls from Github. Currently it will pull any version down including pre-releases. You can test it by changing the api URL to my fork of imagr. https://github.com/clburlison/imagr/tree/makefile-github-release?files=1

**Comment by grahamgilbert** [comment]
Do a pull request and we'll move the conversation for the Makefile there. I have a suggestion, but it's best not to clutter up this issue.

**Comment by grahamgilbert** [comment]
So, the wiki is done and as is the Makefile. It's all on me to make a tool to validate the config plist (the least important part imo). I'll see if I get chance to do it, but I don't see it as a show stopper to doing an initial release.

**Comment by grahamgilbert** [comment]
Closing this, as we're ready for a release once the last few issues are sorted.
