### ISSUE TITLE
disk mount notifications and possible UI change

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#62]
Imagr should subscribe to the following NSWorkspace notifications: NSWorkspaceDidRenameVolumeNotification, NSWorkspaceDidMountNotification, NSWorkspaceWillUnmountNotification and NSWorkspaceDidUnmountNotification

This would allow for rescanning available volumes "automatically".

I also wonder if perhaps the selection of the target volume doesn't need to be modal, and could just be a pop-up menu on the workflows screen...

I'm envisioning someone running Imagr, sitting at the workflows screen, then opening Disk Utility and repartitioning, or plugging in a USB drive. It would be nice if Imagr "automatically" noticed the change in available volumes and updated its pop-up menu accordingly.

I can work on this if you'd like, though I may not get to it until Monday.

**Comment by grahamgilbert** [comment]
Happy for you to work on it - I think I've seen the choose volume popup twice.
