### ISSUE TITLE
New Reload button and bad imagr_config.plist

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#63]
Easy test. Add an extra </array> undernearth a workflow and use the new Reload Workflows feature.

Imagr will hide all of the buttons and display a "No workflows found in the configuration plist" dialog box. After pressing "Okay" you are presented a blank Imagr with no buttons. Startup Disk will then open.

If you go back to Imagr (after fixing the plist) you can Command+R, but in my testing it still cannot resolve the .plist issue. Reloading Imagr/NBI will fix the issue.

**Comment by grahamgilbert** [comment]
Not sure how to handle this one. If there's a bad config plist, what are we supposed to do? We have nothing to work on, a bad config is something that will stop the app from functioning.

**Comment by grahamgilbert** [comment]
I think I've come up with a good solution to this (now I've actually put a bit of thought into it!). Let me know.

**Comment by erikng** [comment]
This is very similar to what I was going to propose this morning. 

Should it be "restart" or open start up disk? Or perhaps have all three options? It's not necessarily clear what will happen when you restart.

**Comment by grahamgilbert** [comment]
Changed it to "Choose Startup Disk".
