### ISSUE TITLE
Please look at my fork

### ISSUE THREAD

**Issue by gregneagle** [grahamgilbert/imagr#70]
Just opening an issue so this doesn't get forgotten

https://github.com/gregneagle/imagr

If you like the direction, I can open a pull request.

Main changes:

1) Imagr subscribes to NSWorkspace notifications to be notified when a new volume is mounted, an existing volume is unmounted, or a volume is renamed.

2) Target disk selection is moved to a popup menu in the same view as the workflow selection.

3) Other UI elements moved in the workflow selection view: Run Workflow moved to lower right, where an OK, Save, or other default "Perform the action" button is usually located in dialogs and assistant-type utilties. Other elements moved to adjust.

**Comment by grahamgilbert** [comment]
I like the general idea. The layout is a bit hard to read at the top - maybe a panel or something so the labels are easier to read? Also, it beach balls when a new volume is mounted. I don't think this will be much of a problem in practise as most will be imaging internal volumes, but it would be good to get it on it's own thread with some feedback on what it's doing.

**Comment by gregneagle** [comment]
The NSWorkspace notifications actually have the info on volumes being mounted and unmounted; we don't really need to go through the lengthy task of rescanning for volumes, but I did it for this initial stab because it was easy.

If we don't scan, but just add or remove or rename the one volume it should be pretty fast.

Or, yes, we could rescan.

I still think (as I mentioned in a previous issue) that the code that builds the list of available volumes could be optimized as well -- it's dreadfully slow.

As for the cosmetic issues, those are easily addressed in many possible ways.

**Comment by grahamgilbert** [comment]
Make a pull request. These issues can be worked through once it's merged in. I have other GUI tweaks to make so it will be easier to start those after this is merged than try to smush them together.

**Comment by grahamgilbert** [comment]
Closing as this was merged in #71
