### ISSUE TITLE
No writable volume found after workflow failure & subsequent workflow reload

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#79]
This is in reference to https://github.com/grahamgilbert/imagr/issues/64 and https://github.com/grahamgilbert/imagr/issues/75

When testing this, I changed the url path to the DMG to a 404. After failing to clone, Imagr offered to "reload the workflows". After reloading I was presented a "No writable volumes found" error.

This is due to the volume being unmounted but not remounted after a failure.

**Comment by grahamgilbert** [comment]
Pull the latest code, this should solve it.

**Comment by erikng** [comment]
First test worked but trying it additionally caused Imagr not to remount the volume. Odd.

**Comment by grahamgilbert** [comment]
Ok, this is my last try. I can't think of any other way to solve this. Every volume that's known is checked and mounted if needed.

**Comment by erikng** [comment]
Latest commit now behaves similar to your commit from a few hours ago.
:/

**Comment by grahamgilbert** [comment]
Definitely fixed, actually tested it this time rather than guessing.

**Comment by erikng** [comment]
May I ask how you are testing this? I pulled the latest version and it fails to pull the image, then still gives the warning without remounting the volume.

**Comment by grahamgilbert** [comment]
Make nbi BUILD=Testing

Run an image workflow that has a url that will 404, run said workflow. Open disk utility and confirm that volume is mounted.

**Comment by erikng** [comment]
I'm going to make a new nbi instead of make update to just to be sure.

**Comment by erikng** [comment]
Perhaps someone else can validate this. It's still not working for me.

My test workflow is only an AutoDMG.

**Comment by clburlison** [comment]
@erikng The issue you are describing is resolved on my side using the latest commit. 

https://www.dropbox.com/s/rffzx1yz3711h5u/imagr_image_error.mov?dl=0

**Comment by erikng** [comment]
Talking in IRC, my particular volume is CoreStorage. The last Imagr deployment I ran had a workflow script to convert it to CoreStorage.

Perhaps this is the difference.

**Comment by erikng** [comment]
[13:13:51] <vmiller> it seems CS is the reason.

Validation.

**Comment by vmiller** [comment]
@erikng  That seems to be it!  Dropped into Terminal in my test VM and converted the volume to Core Storage and now I see "No writable volumes found" after reloading workflows.

**Comment by grahamgilbert** [comment]
This looks like an issue with diskutil itself. If someone can help find the correct command, this will easily be fixed. On a R/W disk image that has been converted to CoreStorage:

```
$ diskutil mountDisk disk3
> Volume(s) mounted successfully
```

Which is a lie!

**Comment by grahamgilbert** [comment]
Who just pushed a fix for this? That's right, I did! Long story short, diskutil was always identifying it as a whole disk, regardless of whether it is or not (which it's not). We're only ever dealing with volumes at the moment and not whole disks, so I took out the check that determines whether we need `diskutil mount` or `diskutil mountDisk`.

Test and confirm fixed for you guys.

**Comment by erikng** [comment]
Working. PR now up as well.
