### ISSUE TITLE
Makefile Validate

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#80]
I'm not sure it is necessary to include the `validateplist` script with the dmg. We are currently instructing users to git clone the repo from the wiki which will download the most up to date script. 

Other thought would be to include the `Makefile` which allows users to avoid git clone altogether.

Not sure what best practice would be...Imagr is in early development so I'll let you decide.

**Comment by grahamgilbert** [comment]
Way ahead of you: https://github.com/grahamgilbert/imagr/releases/tag/v0.0.1-beta.5
