### ISSUE TITLE
Small visual bug on Target Selection

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#84]
I have only seen this happen on physical clients and even then only a handful of times. After typing the password the main window loads however the "Choice Target" is blank. These machines only have one partition and Imagr is successfully resolving that partition (you are able to run the workflow with success). However the GUI element does not display the currently selected target disk.

Out of 40 clients (50 more tomorrow) I have seen this happen 4 times so enough that something is funky.

Build 240. Using AutoNBI NetInstall environment. 

I can try and get more debug info if need just have to finish this roll out first.

**Comment by grahamgilbert** [comment]
Yes, I'll need some more info on how to reproduce before I can start troubleshooting. Disk layout / type of the drives etc would be a start.

**Comment by clburlison** [comment]
Alright, I tired for 30 minutes to reproduce this issue without success. I have only seen this on iMacs with Fusion drives. Not sure if anyone else can chime in but as of this moment I'm not sure what the issue could be.

``` bash
hostname:~ username$ diskutil list
/dev/disk0
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *121.3 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:          Apple_CoreStorage                         121.0 GB   disk0s2
   3:                 Apple_Boot Boot OS X               134.2 MB   disk0s3
/dev/disk1
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *1.0 TB     disk1
   1:                        EFI EFI                     209.7 MB   disk1s1
   2:          Apple_CoreStorage                         999.3 GB   disk1s2
   3:                 Apple_Boot Recovery HD             650.1 MB   disk1s3
/dev/disk2
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:                  Apple_HFS Macintosh HD           *1.1 TB     disk2
                                 Logical Volume on disk0s2, disk1s2
                                 654AAC04-A22B-4250-9BE8-6288BA08A08C
                                 Unencrypted Fusion Drive
```

**Comment by grahamgilbert** [comment]
Is this still a problem @clburlison ? Can I close the issue?

**Comment by clburlison** [comment]
I haven't seen it happen again. Nor was I able to reproduce it.
