### ISSUE TITLE
Optional support for HTTPS (verify server cert, possibly client cert in the future?)

### ISSUE THREAD

**Issue by natewalck** [grahamgilbert/imagr#9]
From Graham: Using Gurl would get us server side verification

**Comment by gregneagle** [comment]
Also SNI support, which is not part of the libraries available in Python 2.6 and 2.7 including Requests. SNI is important for virtual web hosts.

**Comment by grahamgilbert** [comment]
@gregneagle Has this been solved with the move to gurl.py?

**Comment by gregneagle** [comment]
That's for others to test and confirm, but gurl.py does fully support HTTPS, including SNI.

**Comment by grahamgilbert** [comment]
Has passed all the tests I've thrown at it, unless someone wants to re-open it I'm calling this solved.
