### ISSUE TITLE
Optional script task name

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#90]
(this is so I don't forget).

Optional feature for script task names to allow more verbose messaging for Imagr-server.

**Comment by niklasskoldmark** [comment]
+1

**Comment by grahamgilbert** [comment]
I guess you forgot @erikng ?

**Comment by erikng** [comment]
To be honest I now only use imagr for installing base images and I don’t use imagr server. I doubt I’ll have the bandwidth to do this so you can close if you want.
