### ISSUE TITLE
Computer name change isn't working

### ISSUE THREAD

**Issue by efranklin** [grahamgilbert/imagr#92]
I'm using the following in the workflow to prompt for computer name:

```
    <dict>
        <key>type</key>
        <string>computer_name</string>
    </dict>
```

The name is being set to iMac instead of the inputted name.. The OS the netinstall image was created on was OS X 10.10.4. The computers are the latest revision iMac's with fusion drives.

Not sure what logs to check to see what's it's trying to do.

**Comment by clburlison** [comment]
Hey @efranklin, I haven't imaged a computer since June but last time I used the same workflow you are referring to without error. The firstboot log is located at `/var/log/first-boot.log`.

**Comment by grahamgilbert** [comment]
What name are you using? The script to set the name is literally

``` bash
#!/bin/bash

NAME="{{computer_name}}"

/usr/sbin/scutil --set ComputerName "$NAME"
/usr/sbin/scutil --set HostName "$NAME"
/usr/sbin/scutil --set LocalHostName "$NAME"
```

So it's possible we need to do some more parsing to eliminate invalid names, but that remains to be seen

I just Imaged a basic VM (10.10.4, clear reg package and an admin user) and it worked as expected
<img width="1392" alt="screenshot 2015-07-30 10 01 30" src="https://cloud.githubusercontent.com/assets/1208495/8979516/31a6e5c8-36a2-11e5-9c4f-17dc1c1fdbb3.png">

As Clayton said, the logs will be helpful.

**Comment by efranklin** [comment]
I won't be back to that location until Friday and I'll get you the logs then. This is one of the names I've tried to use: AB355-180180

**Comment by efranklin** [comment]
I figured out why it wasn't working. I initially put the "computer_name" script as the first item in the "components" array. I moved it after the "image" script and it worked fine. Is this expected behavior?

Also, the "computer_name" script doesn't show in the "first-boot.log" file.

**Comment by grahamgilbert** [comment]
Yes, expected behaviour. Workflow components are applied in the order they are specified in the plist. The only reason you are asked for a name prior to imaging is I didn't want to have to wait around!

Graham Gilbert

**Comment by efranklin** [comment]
Good to know. Thank you for your help.
