### ISSUE TITLE
Set $3 for script task

### ISSUE THREAD

**Issue by niklasskoldmark** [grahamgilbert/imagr#95]
Hi, thanks for making imagr!
Were in the process of replacing DeployStudio with imagr and I have a few suggestions for improvements. I'm braking them up to different issues so you can consider them separately
It would be really nice if the $3 variable was set for script tasks.
I know i can use {{target_volume}} but it would be nice to be able to just use legacy scripts.

**Comment by grahamgilbert** [comment]
Positional arguments won't be trivial to implement. I'd say using find and replace in your editor is likely to be easier!

**Comment by niklasskoldmark** [comment]
Ah ok.
Is it easier to implement #97? (a run script task with $3 included)
Right now i use a script-task to curl the sourced script (with the third argument set to {{target_volume}})
This achieves the same result but its not easy to understand at a glance since the tasks can't be named (or can they? would i mess something up in image if i just added a name key to a task?)

With DeployStudio I would setup the tasks, component-workflows and a few main workflows and then I could instruct technicians who don't grasp the whole concept to create their own workflows by just "building Lego" with my assemblied pieces.

**Comment by grahamgilbert** [comment]
No, it's no easier because we pass the script to subprocess, not called from disk. I don't think this is something that I'll be able to implement.
