### ISSUE TITLE
Add include workflow task

### ISSUE THREAD

**Issue by niklasskoldmark** [grahamgilbert/imagr#96]
It would be nice to be able to include a workflow by name to another workflow.
Perhaps this would be best implemented if there was a hidden flag in the top dictionary of workflows.
So we can create workflows only meant for inclusion.

**Comment by grahamgilbert** [comment]
Yes, this has been discussed before. Assigning workflow a uuid is the first step. Definitely on the list.

**Comment by niklasskoldmark** [comment]
Is that necessary, aren't the workflow names implemented as unique identifiers? When I've copied and pasted a workflow to try something out and forgotten to change the name, only one of the workflows show up in the drop down.

**Comment by erikng** [comment]
No they are not currently, which is why that happens.

**Comment by grahamgilbert** [comment]
This is why the validation script will fail if you don't use unique names.

**Comment by grahamgilbert** [comment]
This has been implemented
