### ISSUE TITLE
add script-file task

### ISSUE THREAD

**Issue by niklasskoldmark** [grahamgilbert/imagr#97]
I would like to be able to just reference a script on the web server preferably with the install volume passed to the script as $3.
This would remove the pain of xml proofing it and the messiness of pasting the scripts in to the workflow

**Comment by grahamgilbert** [comment]
This has already been implemented in #94.

**Comment by niklasskoldmark** [comment]
Thats wonderful news!
Is it possible to pass parameters to the scrips?

**Comment by grahamgilbert** [comment]
Not in the way you mean, no. Something else is planned, but I'm not committing to anything until I can see what is possible.
