### ISSUE TITLE
workflow task : copy file from server

### ISSUE THREAD

**Issue by niklasskoldmark** [grahamgilbert/imagr#99]
I would like a task to copy a file from the server to the client, preferable with the options to set owner and permissions, alt inherit from target or source.
I know this is doable with a simple script but it makes it easier to understand the workflow at a glance

**Comment by grahamgilbert** [comment]
Why wouldn't you use a package for this? I'm going to need a lot of convincing for this one.

**Comment by niklasskoldmark** [comment]
I would and I do for .AppleSetupDone and the munki-kickstart for example
I think a lot of organizations have the concept of the senior technician who sets up, configures and understands the solution vs the junior technicians who manages the solutions with the tools and templates developed by the senior technician. 
I think the best way of managing this is by modularizing things a bit. 
That's why I think it's a good idea to have some more defined tasks even if it can be solved by using the available tools.
Maybe a "script-task" that runs a script with parameters set in the tasks dictionary could solve a lot of this. That would provide an easy way for administrators to develop reusable DeployStudio-like plugins that copies files, sets keyboard, region and language and so on. This would also allow us to easily use the scripts we use in other parts of management without having to convert them to xml-safe

**Comment by groob** [comment]
> Maybe a "script-task" that runs a script with parameters set in the tasks dictionary could solve a lot of this. That would provide an easy way for administrators to develop reusable DeployStudio-like plugins that copies files, sets keyboard, region and language and so on. This would also allow us to easily use the scripts we use in other parts of management without having to convert them to xml-safe

Is there a reason these things can't be part of your Munki or Casper repo? 
We've been using Imagr for a while now, and one of the main reasons for the switch was how barebones it's features are: 
Install a DMG or Package on machine > Let Munki do the rest. 

IMO Imagr should be a lightweight imaging tool for thin imaging, and not try to duplicate all the DeployStudio features which are better handled by Puppet/Munki/Casper.

**Comment by gregneagle** [comment]
"I would like a task to copy a file from the server to the client, preferable with the options to set owner and permissions, alt inherit from target or source."

This is an ideal task for a package. No reason for Imagr to gain additional complexity.

**Comment by grahamgilbert** [comment]
Agreed. I'm not implementing this - you should use a package for this, it's built in and already does the task better than I could.

**Comment by cozturk** [comment]
Hi,
I am a very new user with Imagr and I want to copy some files/folders to client's machine during the imaging as well. I'm okay to do with packages, as Graham suggested, but don't know how to do it. Is there some kind of instructions for this? I appreciate in advance.

**Comment by grahamgilbert** [comment]
https://github.com/munki/munki-pkg#munkipkg

**Comment by cozturk** [comment]
Thank you Graham for the munkipkg suggestion. I am successfully using the Imagr but having a different issue. This might be already explained somewhere and if so, I apologize for asking again. :) 
In my workflow I have some scripts that need to run after the first boot. If some reason any of those scripts are broken or unsuccessful, after the first-boot, Imagr installation screen keep trying to run the broken script. I can't skip or disable the Imagr screen at that point. All I want is Imagr to ignore the script and go to next item or stop completely so I can start working on the system. 
![img_5948](https://user-images.githubusercontent.com/40611844/42473927-ce90acd4-837a-11e8-93c0-579ff4efb51d.jpg)

Thank you once again.
